# FONT

[font]
size = 12.0
#offset = { x = 1, y = 1 }
glyph_offset = { x = 0, y = 0 }

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

# WINDOW

[window]
padding = { x = 0, y = 0 }
dynamic_padding = false
decorations = "None"
opacity = 0.6
blur = true
decorations_theme_variant = "Dark"

[scrolling]
multiplier = 5

# [colors]
# transparent_background_colors = true

[selection]
save_to_clipboard = true

[cursor]
blink_interval = 400
blink_timeout = 0

[cursor.style]
blinking = "Always"
shape = "Beam"

[mouse]
hide_when_typing = true
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
]
